### ISSUE TITLE
Running together with firebase_ml_vision

### ISSUE THREAD

**Issue by Martin-Pucalka** [rishab2113/firebase_mlkit_language#34]
When I try to add firebase_ml_vision package to the example app, I get following error:

> ...
> [ +721 ms] Dependency resolved to an incompatible version:
> Dependency(fromArtifactVersion=ArtifactVersion(groupId=com.google.firebase, artifactId=firebase-ml-vision,
> version=20.0.0), toArtifact=Artifact(groupId=com.google.firebase, artifactId=firebase-ml-common),
> toArtifactVersionString=[19.0.0])
> [  +12 ms]          *********************************************************
> [   +2 ms] WARNING: This version of firebase_mlkit_language will break your Android build if it or its dependencies
> aren't compatible with AndroidX.
> [   +4 ms]          See https://goo.gl/CP92wY for more information on the problem and how to fix it.
> [   +2 ms]          This warning prints for all Android build failures. The real root cause of the error may be
> unrelated.
> [   +2 ms]          *********************************************************
> [ +667 ms] Running Gradle task 'assembleDebug'... (completed in 4,7s)
> [   +5 ms] "flutter run" took 14 501ms.
> Gradle task assembleDebug failed with exit code 1
> 
> #0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
> #1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:751:5)
> <asynchronous suspension>
> #2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:494:14)
> <asynchronous suspension>
> #3      buildApk (package:flutter_tools/src/android/apk.dart:34:9)
> <asynchronous suspension>
> #4      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:486:13)
> <asynchronous suspension>
> #5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:378:54)
> <asynchronous suspension>
> #6      HotRunner.run (package:flutter_tools/src/run_hot.dart:254:39)
> <asynchronous suspension>
> #7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:472:37)
> <asynchronous suspension>
> #8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
> #9      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
> #10     _rootRunUnary (dart:async/zone.dart:1132:38)
> #11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
> #12     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
> #13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
> #14     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
> #15     Future._completeWithValue (dart:async/future_impl.dart:522:5)
> #16     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
> #17     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
> #18     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
> #19     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
> #20     _rootRunUnary (dart:async/zone.dart:1132:38)
> #21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
> #22     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
> #23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
> #24     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
> #25     Future._completeWithValue (dart:async/future_impl.dart:522:5)
> #26     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
> #27     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
> #28     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
> #29     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
> #30     _rootRunUnary (dart:async/zone.dart:1132:38)
> #31     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
> #32     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
> #33     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
> #34     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
> #35     Future._completeWithValue (dart:async/future_impl.dart:522:5)
> #36     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
> #37     _rootRun (dart:async/zone.dart:1124:13)
> #38     _CustomZone.run (dart:async/zone.dart:1021:19)
> #39     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
> #40     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
> #41     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
> #42     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
> #43     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
> #44     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)`

Steps to reproduce:
- added firebase_ml_vision to example/pubspec.yaml:
 `firebase_ml_vision: ^0.9.3+3`

- updated gradle version in gradle-wrapper.properties
 `distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip`
 
- added my google-services.json and changed applicationId in example/android/app/build.gradle

How can I fix this? Thank you.

**Comment by XinyueZ** [comment]
Actually, this project needs an upgrade according to the latest update of the firebase library.
There is an issue #33 which concerns the same like this ticket.

**Comment by Martin-Pucalka** [comment]
I updated to ML Kit Natural Language version 22.0.0 in #35 . Maybe it'll need some changes, because I'm new to flutter, but it seems to be working. Anyway I'm still getting this error, when I try to include firebase_ml_vision.

**Comment by bobba-sai-rohith** [comment]
> Actually, this project needs an upgrade according to the latest update of the firebase library.
> There is an issue #33 which concerns the same like this ticket.

is there any other chance of accessing firebase mlkit ondevice translation using Flutter
